In [1]:
import numpy as np

In [2]:
# Multi-Layer Perceptron (MLP)

# Input Layer

In [3]:
# Step 0: Read input and output
X = np.array([[1,0,1,0],
              [1,0,1,1],
              [0,1,0,1]])
y = np.array([[1],[1],[0]])

# Forward Propogation

In [4]:
# Step 1: Initialize weights and biases with random values

# wh is the weight matrix to the hidden layer
# bh is the bias matrix to the hidden layer
wh = np.array([[0.42,0.88,0.55],
               [0.10,0.73,0.68],
               [0.60,0.18,0.47],
               [0.92,0.11,0.52]])
bh = np.array([[0.46,0.72,0.08]])

# wout is the weight matrix to the output layer
# bout is the bias matrix to the output layer

wout = np.array([[0.30],
                 [0.25],
                 [0.23]])
bout = np.array([[0.69]])

In [5]:
# Step 2: Calculate hidden layer input
hidden_layer_input = np.dot(X,wh) + bh
hidden_layer_input

array([[1.48, 1.78, 1.1 ],
       [2.4 , 1.89, 1.62],
       [1.48, 1.56, 1.28]])

In [6]:
# Step 3: Perform non-linear transformation on hidden linear input
def sigmoid(x): return 1/(1+np.exp(-x))
hidden_layer_activations = sigmoid(hidden_layer_input)
hidden_layer_activations

array([[0.81457258, 0.85569687, 0.75026011],
       [0.9168273 , 0.86875553, 0.83479513],
       [0.81457258, 0.82635335, 0.78244978]])

In [7]:
# Step 4: Perform linear and non-linear transformation of hidden layer 
# activation at output layer

output_layer_input = np.dot(hidden_layer_activations,wout) + bout
output = sigmoid(output_layer_input)
output

array([[0.78932406],
       [0.79806432],
       [0.78933532]])

# Back Propogation

In [8]:
# Step 5: Calculate gradient of Error(E) at output layer
E = y - output
E

array([[ 0.21067594],
       [ 0.20193568],
       [-0.78933532]])

In [9]:
# Step 6: Compute slope at output and hidden layer
def derivatives_sigmoid(x): return x * (1-x)

slope_hidden_layer = derivatives_sigmoid(hidden_layer_activations)
slope_output_layer = derivatives_sigmoid(output)

print('slope_hidden_layer')
print('')
print(slope_hidden_layer)
print('')
print('slope_output_layer')
print('')
print(slope_output_layer)

slope_hidden_layer

[[0.15104409 0.12347974 0.18736988]
 [0.076255   0.11401936 0.13791222]
 [0.15104409 0.14349349 0.17022212]]

slope_output_layer

[[0.16629159]
 [0.16115766]
 [0.16628507]]


In [10]:
# Step 7: Compute delta at output layer
lr = 1

d_output = E * slope_output_layer*lr
d_output

array([[ 0.03503364],
       [ 0.03254348],
       [-0.13125468]])

In [11]:
# Step 8: Calculate Error at hidden layer

Error_at_hidden_layer = np.dot(d_output,wout.T)
Error_at_hidden_layer

array([[ 0.01051009,  0.00875841,  0.00805774],
       [ 0.00976304,  0.00813587,  0.007485  ],
       [-0.0393764 , -0.03281367, -0.03018858]])

In [12]:
# Step 9: Compute delta at hidden layer

d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
d_hiddenlayer

array([[ 0.00158749,  0.00108149,  0.00150978],
       [ 0.00074448,  0.00092765,  0.00103227],
       [-0.00594757, -0.00470855, -0.00513876]])

In [13]:
lr = 0.1

wout = wout + np.dot(hidden_layer_activations.T, d_output)*lr
wh =  wh+ np.dot(X.T,d_hiddenlayer)*lr

print('wout')
print(wout)
print('wh')
print(wh)

wout
[[0.29514577]
 [0.24497878]
 [0.22507513]]
wh
[[0.4202332  0.88020091 0.55025421]
 [0.09940524 0.72952915 0.67948612]
 [0.6002332  0.18020091 0.47025421]
 [0.91947969 0.10962191 0.51958935]]


In [14]:
d_hiddenlayer

array([[ 0.00158749,  0.00108149,  0.00150978],
       [ 0.00074448,  0.00092765,  0.00103227],
       [-0.00594757, -0.00470855, -0.00513876]])

In [16]:
np.sum(d_hiddenlayer, axis=0)

array([-0.00361561, -0.00269942, -0.00259671])

In [22]:
bh = bh + np.sum(d_hiddenlayer, axis=0) * lr
bout = bout + np.sum(d_output, axis=0)*lr

print('Hidden Layer Bias')
print(bh)
print('')
print('Output Layer Bias')
print(bout)

Hidden Layer Bias
[[0.4581922  0.71865029 0.07870164]]

Output Layer Bias
[[0.65816122]]


In [28]:
import numpy as np

#Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y=np.array([[1],[1],[0]])

#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

#Variable initialization
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):

    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)

    #Backpropagation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr
    if i % 100 == 0:
        print('Epoch # {}'.format(i))
        print(output)

Epoch # 0
[[0.71399199]
 [0.73082096]
 [0.72711947]]
Epoch # 100
[[0.66620709]
 [0.67916797]
 [0.67131047]]
Epoch # 200
[[0.66928694]
 [0.68096309]
 [0.66725561]]
Epoch # 300
[[0.67351585]
 [0.68452397]
 [0.6632137 ]]
Epoch # 400
[[0.67923233]
 [0.68972196]
 [0.65641925]]
Epoch # 500
[[0.68817088]
 [0.69775873]
 [0.64199977]]
Epoch # 600
[[0.70497584]
 [0.71191786]
 [0.60624997]]
Epoch # 700
[[0.73972803]
 [0.73898187]
 [0.52600391]]
Epoch # 800
[[0.79015516]
 [0.77803212]
 [0.42335792]]
Epoch # 900
[[0.83515796]
 [0.81546933]
 [0.33898361]]
Epoch # 1000
[[0.86761703]
 [0.84476242]
 [0.2786968 ]]
Epoch # 1100
[[0.89011345]
 [0.86641673]
 [0.23642156]]
Epoch # 1200
[[0.9060314]
 [0.8825083]
 [0.2060138]]
Epoch # 1300
[[0.91770068]
 [0.89476218]
 [0.18334831]]
Epoch # 1400
[[0.92655958]
 [0.90435165]
 [0.16587283]]
Epoch # 1500
[[0.93349377]
 [0.91204659]
 [0.1520011 ]]
Epoch # 1600
[[0.93906343]
 [0.91835723]
 [0.14071811]]
Epoch # 1700
[[0.94363509]
 [0.92362974]
 [0.13135187]]
Epoch #